wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.2
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      4: 3.8.8
      5: 0.11.2
      8:
      - 1
      - 3
      - 5
colsample_bytree:
  desc: null
  value: 0.7292639877332963
max_depth:
  desc: null
  value: 15
subsample:
  desc: null
  value: 0.9889245231389854
