wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      4: 3.8.8
      5: 0.11.2
      8:
      - 1
      - 3
      - 5
